// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/thepenn/devsys/internal/cache"
	"github.com/thepenn/devsys/internal/config"
	"github.com/thepenn/devsys/internal/handler"
	"github.com/thepenn/devsys/internal/server"
	"github.com/thepenn/devsys/internal/store"
	"github.com/thepenn/devsys/routers"
	"github.com/thepenn/devsys/routers/middleware/admin"
	"github.com/thepenn/devsys/routers/middleware/auth"
	"github.com/thepenn/devsys/routers/middleware/metrics"
	"github.com/thepenn/devsys/service"
	"github.com/thepenn/devsys/service/migrate"
	"github.com/thepenn/devsys/service/pipeline/queue"
	"time"
)

// Injectors from wire.go:

func WireApp(cfg *config.Config) (*App, error) {
	db, err := InjectedDatabase(cfg)
	if err != nil {
		return nil, err
	}
	pipelineQueue := InjectedQueue(cfg)
	cache := InjectedCache()
	services, err := InjectedServices(db, pipelineQueue, cache, cfg)
	if err != nil {
		return nil, err
	}
	middleware := InjectedAuthMiddleware(services)
	routers := InjectedRouters(cfg, services, middleware)
	adminMiddleware := InjectedAdminMiddleware(services)
	metricsMiddleware := InjectedMetricsMiddleware()
	handler := InjectedHandler(cfg, routers, middleware, adminMiddleware, metricsMiddleware)
	httpServer := InjectedHttpServer(cfg, handler)
	app := NewApp(httpServer, services, db, cache)
	return app, nil
}

// wire.go:

type App struct {
	HttpServer *server.HttpServer
	Services   *service.Services
	DB         *store.DB
	Cache      *cache.Cache
}

// NewApp 创建应用实例
func NewApp(httpServer *server.HttpServer, services *service.Services, db *store.DB, cache2 *cache.Cache) *App {
	return &App{
		HttpServer: httpServer,
		Services:   services,
		DB:         db,
		Cache:      cache2,
	}
}

var appSet = wire.NewSet(
	InjectedRouters,
	InjectedHandler,
	InjectedHttpServer,
	InjectedDatabase,
	InjectedCache,
	InjectedQueue,
	InjectedServices,
	InjectedMetricsMiddleware,
	InjectedAdminMiddleware,
	InjectedAuthMiddleware,
	NewApp,
)

func InjectedRouters(cfg *config.Config, services *service.Services, authMiddleware *auth.Middleware) *routers.Routers {
	return routers.NewRouters(cfg, services, authMiddleware)
}

func InjectedHandler(cfg *config.Config, routers2 *routers.Routers, authMiddleware *auth.Middleware, adminMiddleware *admin.Middleware, metric *metrics.Middleware) *handler.Handler {
	return handler.NewHandler(handler.WithConfig(cfg.Server.Host, cfg.Server.RootPath), handler.WithRegisterControllers(routers2), handler.WithRegisterMiddlewares(authMiddleware), handler.WithRegisterMiddlewares(adminMiddleware), handler.WithRegisterMiddlewares(metric))
}

func InjectedHttpServer(cfg *config.Config, h *handler.Handler) *server.HttpServer {
	return server.NewHttpServer(cfg.Server.Host, h.Handler())
}

func InjectedDatabase(cfg *config.Config) (*store.DB, error) {
	db, err := store.Connect(cfg.Database.Datasource, cfg.Database.MaxConnections, cfg.Database.ShowSql)
	if err != nil {
		return nil, err
	}
	if err := migrate.AutoMigrate(db); err != nil {
		return nil, err
	}
	return db, nil
}

func InjectedCache() *cache.Cache {
	return cache.New(5 * time.Minute)
}

func InjectedQueue(cfg *config.Config) *queue.PipelineQueue {
	return queue.New(cfg.Pipeline.QueueCapacity)
}

func InjectedServices(db *store.DB, q *queue.PipelineQueue, cache2 *cache.Cache, cfg *config.Config) (*service.Services, error) {
	return service.NewServices(db, q, cache2, cfg)
}

func InjectedMetricsMiddleware() *metrics.Middleware {
	return metrics.New()
}

func InjectedAdminMiddleware(services *service.Services) *admin.Middleware {
	return admin.New(services.User)
}

func InjectedAuthMiddleware(services *service.Services) *auth.Middleware {
	return auth.New(services.Auth)
}
